---

此文件为配置文件模板，更新时将覆盖。
配置文件为 config.yaml，首次运行时自动生成。

---
device:
  # ADB server 的端口。部分模拟器为避免冲突可能会将 ADB server 开在其他端口，
  # 此时可以更改此设置以利用模拟器自带的 ADB server。
  # adb_server: 127.0.0.1:5037

  # 需要启动 adb server 时，使用的 adb 命令
  # 为空时则尝试: 1. PATH 中的 adb；
  #               2. ADB/{sys.platform}/adb;
  #               3. 查找 Android SDK（ANDROID_SDK_ROOT 和默认安装目录）
  adb_binary:
  # 以下为部分模拟器提供的 adb 程序，不一定正确，仅供参考
  # adb_binary: D:\leidian\LDPlayer\adb.exe             # 雷电模拟器
  # adb_binary: C:\Program Files\BlueStacks\HD-Adb.exe  # BlueStacks
  # adb_binary: C:\Program Files (x86)\MuMu\emulator\nemu\vmonitor\bin\adb_server.exe  # MuMu模拟器

  # 始终选择指定设备进行操作（指定 adb devices 中列出的名称）
  # adb_always_use_device:

  # 无设备连接时进行的操作
  # 如果某个操作报告成功，则不再执行后续定义的操作
  adb_no_device_fixups:
  - run: probe_bluestacks_hyperv  # 自动探测并连接 BlueStacks Hyper-V 的 ADB 端口
  - run: adb_connect  # 连接 ADB TCP/IP 端口
    target: 
      - 127.0.0.1:5555  # 大部分模拟器
      - 127.0.0.1:7555  # MuMu模拟器
    try_all: false  # 某个端口连接成功后，是否继续尝试后续定义的端口

  # 使用兼容性较好（但较慢）的截图方式
  compat_screenshot: false

  # 通过 adb 传输模拟器截图数据较慢时，尝试绕过 adbd 传输截图数据
  # 模拟器判断逻辑：1. 设备名称以 "emulator-" 或 "127.0.0.1:" 开头
  #                 2. ro.product.board 包含 goldfish（SDK emulator）或存在 vboxguest 模块
  # 可用选项：never, auto, always
  workaround_slow_emulator_adb: auto

  # 截图缓存：如果两次截图间隔小于上次截图耗时，则直接返回上次的截图
  cache_screenshot: true

  package_name: com.hypergryph.arknights
  activity_name: com.u8.sdk.U8UnityContext

ocr:
  # 选择 OCR 引擎，必要
  # 设置为 auto 则选择下列第一个可用的引擎: tesseract, windows_media_ocr, baidu
  engine: auto

  # 百度 API 设置，使用 baidu OCR 时需要正确填写
  baidu_api:
    # 是否将百度 OCR 标记为可用
    enabled: false
    # 百度 API 鉴权数据
    app_id: STUB
    app_key: STUB
    app_secret: STUB

